goinghugh/urls.py
from django.conf.urls import url
from django.contrib import admin
from django.conf.urls.static import static
from django.conf import settings
from django.contrib.auth.views import logout
from blogs.views import index,blog,new_blog_form,new_blog_post,index_login,index_register,article_to_blog

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^$', index,name='index'),
    url(r'^blog/(?P<page>\d+)/$', blog,name='blog'),
    url(r'^comment/(?P<id>\d+)/$', article_to_blog,name='comment'),
    url(r'^new_blog/$', new_blog_form,name='new_blog_form'),
    url(r'^post_blog/$', new_blog_post,name='new_blog_post'),
    url(r'^login/$', index_login,name='login'),
    url(r'^logout/$', logout,{'next_page':'/'},name='logout'),
    url(r'^register/$', index_register,name='register'),

]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL,document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

blogs/models.py
from django.db import models

# Create your models here.
class Blogs(models.Model):
    title = models.CharField(max_length=200)    #文章标题
    blog_digest = models.TextField(null=True,blank=True,max_length=200)      #摘要文本
    blog_content = models.TextField(null=True,blank=True)   #博客内容
    createtime = models.DateTimeField(auto_now_add=True)    #创建时间
    blog_img = models.URLField(null=True,blank=True)        #博客图片链接


    def __str__(self):
        return self.title
class Article(models.Model):
    articler = models.CharField(max_length=50)  #评论者姓名
    article_content = models.TextField(max_length=500)  #评论内容
    article_to_blog = models.ForeignKey(to=Blogs,related_name='article_to_blog',blank=True,null=True,on_delete=models.SET_NULL)    #建立评论和内容的关联关系，多对一关系
    article_createtime = models.DateTimeField(auto_now_add=True) #评论创建时间

blogs/forms.py
from django import forms
from django.forms import ModelForm
from blogs.models import Article
from django.core.exceptions import ValidationError
def word_num_validator(number):
    if len(number) < 4:
        raise ValidationError


class NewBlogForm(forms.Form):
    title = forms.CharField(
        label="标题:",
        max_length=100,
        validators=[word_num_validator],

    )
    blog_degist = forms.CharField(
        label="摘要",
        max_length=200,
        widget=forms.Textarea
    )
    blog_content = forms.CharField(
        label="内容:",
        widget=forms.Textarea,
        error_messages= {
            "required":'字数过少'
        },
        validators=[word_num_validator]
    )

#从models中导入的Form,fields选择性暴露html的接口
class ArticleForm(ModelForm):
    class Meta:
        model = Article
        # fields = "__all__"
        fields = ['articler','article_content'] #暴露给form的接口

blogs/views.py
from django.shortcuts import render,redirect,HttpResponse
from blogs.models import Blogs,Article
from django.core.exceptions import ObjectDoesNotExist
from blogs.forms import NewBlogForm,ArticleForm
from django.contrib.auth.forms import AuthenticationForm
from django.contrib.auth import login,logout
from django.contrib.auth.decorators import login_required
# Create your views here.

def index(request):
    blog = Blogs.objects.all().order_by("-createtime")
    context = {
        'blogs':blog
    }
    return render(request,"base.html",context=context)
def blog(request,page):
    articleForm = ArticleForm
    try:
        blog_detail = Blogs.objects.get(id = page)
        articles = blog_detail.article_to_blog.all().order_by("-article_createtime")
    except ObjectDoesNotExist:
        return render(request,'404.html')
    context = {
        'blog_detail':blog_detail,
        'article_form':articleForm,
        'articles':articles,
    }
    print(articles)
    return render(request,'blog.html',context=context)
def article_to_blog(request,id):
    if request.method == "POST":
        form = ArticleForm(request.POST)
        if form.is_valid():
            articler_pst = form.cleaned_data['articler']
            article_pst = form.cleaned_data['article_content']
            blog = Blogs.objects.get(id=id)
            print(article_pst,articler_pst)
            a = Article(articler=articler_pst,article_content=article_pst,article_to_blog=blog)
            a.save()
        return redirect(to='blog',page=id)
    return render(request, 'blog.html')
@login_required
def new_blog_form(request):
    form = NewBlogForm
    context = {
        'form':form
    }
    return render(request,'new_blog.html',context = context)

def new_blog_post(request):
    if request.method == "POST":
        form = NewBlogForm(request.POST)
        if form.is_valid():
            title = form.cleaned_data['title']
            blog_digest = form.cleaned_data['blog_degist']
            blog_content = form.cleaned_data['blog_content']
            c = Blogs(title=title,blog_digest=blog_digest,blog_content=blog_content)
            c.save()
            return redirect(to='index')

def index_login(request):
    if request.method == "GET":
        form = AuthenticationForm
    if request.method == "POST":
        form = AuthenticationForm(data=request.POST)
        if form.is_valid():
            login(request,form.get_user())
            return redirect('index')
    context = {
        'form':form
    }
    return render(request,'login.html',context)

def index_register(request):
    logout(request)
    return render(request,'register.html')

blogs/templates/base.html
<!DOCTYPE html>
{% load staticfiles %}
<html>
  <head>
    <meta charset="utf-8">
    <title>goinghugh</title>
    <link rel="stylesheet" href="{% static 'css/semantic.css' %}" media="screen" title="no title" charset="utf-8">
    <link rel="stylesheet" href="{% static 'css/Blogs.css' %}" media="screen" title="no title" charset="utf-8">
    <link rel="stylesheet" href="{% static 'wangEditor/dist/css/wangEditor.min.css' %}" media="screen" title="no title" charset="utf-8">

  </head>
  <body style="background-color: #eeeeee">

    {% block header %}
      <div style="background-color: #2c3e50" class="ui inverted  top menu borderless menu">
        <div class="header item">
          <a href="{% url 'index' %}">
            <img src="{% static 'images/g.png'%}" alt="" />
          </a>

            {% if request.user.is_authenticated %}
              <a href="{% url 'new_blog_form' %}" class="item">写一篇</a>
            {% endif %}
          <a href="#" class="right"></a>
        </div>
        <div class="right menu">
            <div class="item">
                <a href="{% url 'index' %}" class="right item">BLOG</a>
            </div>
            <div class="item">
                <a href="#" class="right item">ABOUT ME</a>
            </div>
            <div class="item"></div>
            <div class="item">
              {% if  request.user.is_authenticated %}
                <a class="ui inverted circular button" href="{% url 'logout' %}">LOGOUT</a>
              {% else %}
                <a class="ui inverted circular button" href="{% url 'login' %}">LOGIN</a>
              {% endif %}

          </div>
        </div>
      </div>

    {% endblock header %}

      <div class="ui vertical basic container segment">
      {% block content %}
        <div class="ui grid">
            <div class="row">
                <div class="twelve wide column">
                    <div class="ui vertical container segment">
                         {% for blog in blogs %}
                            <div class="ui container segment">
                                <a style="font-size: 20px;padding-bottom: 5px;" href="{% url "blog" blog.id %}">
                                    {{ blog.title }}
                                </a>
                                <br>
                                <span style="font-size: 10px">
                                    <i class="calendar icon"></i>
                                    {{ blog.createtime }}
                                </span>
                                {% autoescape off %}
                                    <h6>
                                        {{ blog.blog_digest }}
                                    </h6>
                                {% endautoescape %}
                            </div>
                        {% endfor %}
                    </div>

                </div>
                <div style="display: none" class="three wide column">
                    <div class="ui vertical borderless menu ">
                            <div class="item">
                                标签
                            </div>
                            <div class="ui divider"></div>
                            <div class="item">
                                <a href="#">
                                    <p>
                                        <span class="ui right floated">
                                            python
                                        </span>
                                        <span style="float: right" class="ui right floated">
                                            2
                                        </span>
                                    </p>
                                </a>
                            </div>
                            <div class="item">
                                <a href="#">django</a>
                            </div>
                            <div class="item">
                                <a href="#">django</a>
                            </div>
                            <div class="item">
                                <a href="#">django</a>
                            </div>
                            <div class="item">
                                <a href="#">django</a>
                            </div>
                        </div>
                </div>

            </div>
        </div>
      {% endblock %}

      </div>
    {% block article %}

    {% endblock %}
    {% block footer %}
        <div style="background-color: #2c3e50" class="ui inverted vertical bottom  segment">
            <div class="ui grid container ">
                <div class="eight wide column">
                    Designed by yongxu wang.
                </div>
                <div class="eight wide column">
                    CONTACT ME
                </div>
            </div>
        </div>
    {% endblock %}
  </body>
<script type="text/javascript" src="{% static "wangEditor/dist/js/lib/jquery-1.10.2.min.js" %}"></script>
<script type="text/javascript" src="{% static "wangEditor/dist/js/wangEditor.min.js" %}"></script>
{% block js %}

{% endblock %}

</html>

blogs/templates/blog.html
{% extends 'base.html' %}
{% load staticfiles %}
{% block content %}
    <div class="ui container segment">
        <h1 class="ui header">
            {{ blog_detail.title }}
        </h1>
         <span style="font-size: 10px">
            <i class="calendar icon"></i>
            {{ blog_detail.createtime|date:"Y年m月d日" }}
            {{ blog_detail.createtime|time:"H:i" }}
        </span>
        {% autoescape off %}
        <h6 class="ui header">
            {{ blog_detail.blog_digest }}
            {{ blog_detail.blog_content }}
        </h6>
        {% endautoescape %}
    </div>
{% endblock %}
{% block article %}
    <div class="ui vertical basic container segment" >
       <h3 class="ui horizontal  divider header" style="">Comments</h3>
        <div class="ui segment">
                {% for article in articles %}
                    <div class="ui comments">
                        <div class="content">
                            <a href="#" class="author">{{ article.articler }}</a>
                            <div class="metadata">
                                <div class="date">
                                    {{ article.article_createtime|date:"Y年m月d日" }}
                                    {{ article.article_createtime|time:"H:i" }}
                                </div>
                            </div>
                            <p class="text">
                                {{ article.article_content }}
                            </p>
                            <div class="ui divider"></div>
                        </div>
                    </div>
                {% endfor %}
        <form class="ui error tiny form" action="{% url 'comment' blog_detail.id %}" method="post">
            {% csrf_token %}
            {% for field in article_form %}
                <div class="ui field">
                {{ field.label }}
                {{ field }}
                </div>
            {% endfor %}
            <button type="submit" class="ui blue button">Click</button>
        </form>

{#        <!--PC版-->#}
{#            <div id="SOHUCS" sid="blog_detail.id"></div>#}
{#            <script charset="utf-8" type="text/javascript" src="http://changyan.sohu.com/upload/changyan.js" ></script>#}
{#            <script type="text/javascript">#}
{#                window.changyan.api.config({#}
{#                appid: 'cysMRnkCe',#}
{#                conf: 'prod_84a103b3a13fb90244efa25297e74906'#}
{#                });#}
{#            </script>#}

        </div>
    </div>

{% endblock %}

blogs/templates/index.html
<!DOCTYPE HTML>
<html>
<head>
<title>Home</title>
<!-- Bootstrap -->
<link href="css/bootstrap.min.css" rel='stylesheet' type='text/css' />
<link href="css/bootstrap.css" rel='stylesheet' type='text/css' />
<meta name="viewport" content="width=device-width, initial-scale=1">
<script type="application/x-javascript"> addEventListener("load", function() { setTimeout(hideURLbar, 0); }, false); function hideURLbar(){ window.scrollTo(0,1); } </script>
 <!--[if lt IE 9]>
     <script src="js/html5shiv.js"></script>
     <script src="js/respond.min.js"></script>
<![endif]-->

<link href="css/style.css" rel="stylesheet" type="text/css" media="all" />
<!-- start plugins -->
<script type="text/javascript" src="js/jquery.min.js"></script>
	<script>
		$(function() {
			var pull 		= $('#pull');
				menu 		= $('nav ul');
				menuHeight	= menu.height();
			$(pull).on('click', function(e) {
				e.preventDefault();
				menu.slideToggle();
			});
			$(window).resize(function(){
        		var w = $(window).width();
        		if(w > 320 && menu.is(':hidden')) {
        			menu.removeAttr('style');
        		}
    		});
		});
	</script>
<!----font-Awesome----->
   	<link rel="stylesheet" href="fonts/css/font-awesome.min.css">
<!----font-Awesome----->
</head>
<body>
<div class="header_bg" id="home"><!-- start header -->
<div class="container">
	<div class="row header text-center specials">
		<div class="h_logo">
			<a href="index.html"><img src="images/logo.png" alt="" class="responsive"/></a>
		</div>
		<nav class="top-nav">
			<ul class="top-nav nav_list">
				<li><a href="portfolio.html">portfolio</a></li>
				<li class="page-scroll"><a href="#about">About</a></li>
				<li class="logo page-scroll"><a title="hexa" href="index.html"><img src="images/logo.png" alt="" class="responsive"/></a></li>
			    <li class="page-scroll"><a href="blog.html">blog</a></li>
				<li class="page-scroll"><a href="#contact">get in touch</a></li>
			</ul>
			<a href="#" id="pull"><img src="images/nav-icon.png" title="menu" /></a>
		</nav>
		<div class="clearfix"></div>
	</div>
</div>
</div>
<div class="slider_bg"><!-- start slider -->
<div class="container">
		<div class="row slider">
		<div class="wmuSlider example1"><!-- start wmuSlider example1 -->
			   <div class="wmuSliderWrapper">
				   <article style="position: absolute; width: 100%; opacity: 0;"> 
				  	 	<div class="slider_img text-center">
				   			<ul class="list-unstyled list_imgs">
				   				<li><img src="images/slider.jpg" alt="" class="responsive"/></li>
				   			</ul>
			           	</div>
				   </article>
				   <article style="position: relative; width: 100%; opacity: 1;"> 
				  	 	<div class="slider_img text-center">
				   			<ul class="list-unstyled list_imgs">
				   				<li><img src="images/slider1.jpg" alt="" class="responsive"/></li>
				   			</ul>
			           	</div>
				   </article>
				 </div>
                <ul class="wmuSliderPagination">
                	<li><a href="#" class="">0</a></li>
                	<li><a href="#" class="">1</a></li>
                </ul>
			<script src="js/jquery.wmuSlider.js"></script> 
		     <script>
				 $('.example1').wmuSlider();         
			</script>
        </div><!-- end wmuSlider example1 -->
        <div class="clearfix"></div>
      </div>
</div>
</div>
<div class="main_bg"  id="about"><!-- start about us -->
<div class="container">
	<div class="row about">
		<div class="col-md-3 about_img">
			<img src="images/user.png" alt="" class="responsive"/>
		</div>
		<div class="col-md-9 about_text">
			<h3>smith anderson</h3>
			<h4>illustrator & character designer</h4>
			<p>Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum</p>
			<div class="soc_icons navbar-right">
				<ul class="list-unstyled text-center">
					<li><a href="#"><i class="fa fa-facebook"></i></a></li>
					<li><a href="#"><i class="fa fa-twitter"></i></a></li>
					<li><a href="#"><i class="fa fa-google-plus"></i></a></li>
					<li><a href="#"><i class="fa fa-pinterest"></i></a></li>
					<li><a href="#"><i class="fa fa-linkedin"></i></a></li>
					<li><a href="#"><i class="fa fa-dribbble"></i></a></li>
				</ul>	
			</div>
		</div>
	</div>
</div>
</div>
<div class="footer_bg" id="contact"><!-- start footer -->
<div class="container">
	<div class="row footer">
		<div class="col-md-8 contact_left">
			<h3>get in touch</h3>
			<p>In order to get in touch use the contact form below:</h4>
			<form method="post" action="contact-post.html">
				<input type="text" value="Name (Required)" onFocus="this.value = '';" onBlur="if (this.value == '') {this.value = 'Name';}">
				<input type="text" value="Email (Required)" onFocus="this.value = '';" onBlur="if (this.value == '') {this.value = 'Email';}">
				<input type="text" value="Subject" onFocus="this.value = '';" onBlur="if (this.value == '') {this.value = 'Subject';}">
				<textarea onFocus="if(this.value == 'Your Message here....') this.value='';" onBlur="if(this.value == '') this.value='Your Message here....;" >Your Message here....</textarea>
				<span class="pull-right"><input type="submit" value="submit us"></span>
			</form>
		</div>
		<div class="col-md-4  contact_right">
			<p><span>Lorem Ipsum is simply dummy text: </span> Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. </p>
			<ul class="list-unstyled address">
				<li><i class="fa fa-map-marker"></i><span>500 Lorem Ipsum Dolor Sit,</span></li>
				<li><i class="fa fa-phone"></i><span>(00) 222 666 444</span></li>
				<li><i class="fa fa-envelope"></i><a href="mailto:info@mycompany.com">info(at)mycompany.com</a></li>
			</ul>
		</div>		
	</div>
</div>
</div>
<div class="footer1_bg"><!-- start footer1 -->
	<div class="container">
		<div class="row  footer">
			<div class="copy text-center">
				<p class="link"><span>Copyright &copy; 2014.Company name All rights reserved.<a target="_blank" href="http://www.huiyi8.com/moban/">&#x7F51;&#x9875;&#x6A21;&#x677F;</a></span></p>
				<a href="#home" id="toTop" style="display: block;"><span id="toTopHover" style="opacity: 1;"> </span></a>
			</div>
		</div>
		<script type="text/javascript">
				$(function() {
				  $('a[href*=#]:not([href=#])').click(function() {
				    if (location.pathname.replace(/^\//,'') == this.pathname.replace(/^\//,'') && location.hostname == this.hostname) {
			
				      var target = $(this.hash);
				      target = target.length ? target : $('[name=' + this.hash.slice(1) +']');
				      if (target.length) {
				        $('html,body').animate({
				          scrollTop: target.offset().top
				        }, 1000);
				        return false;
				      }
				    }
				  });
				});
		</script>
		<!---- start-smoth-scrolling---->		
	</div>
</div>

</body>
</html>

blogs/templates/new_blog.html
{% extends 'base.html' %}

{% block content %}
    <form class="ui tiny form" action="{% url "new_blog_post" %}" method="post">
    {% csrf_token %}
        {% for f in form %}
            {{ f.label }}
            {{ f }}
        {% endfor  %}
        <div style="height: 80px">
            <div id="id_blog_content">
            </div>
        </div>
    <button type="submit" class="ui blue button">提交</button>
    </form>
{% endblock %}

{% block js %}
    <script type="text/javascript">
        var editor = new wangEditor('id_blog_content');
        editor.create();
        var editor_digest = new wangEditor("id_blog_degist");
        editor_digest.create();
    </script>
{% endblock %}

blogs/templates/register.html
{% extends 'base.html' %}
<!DOCTYPE html>
{% load staticfiles %}
<html>
    <head>
        <meta charset="utf-8">
        <title></title>
    </head>
    <body>
    {% block content %}
        <div style="margin-top: 100px" class="ui basic center grid divided segment container">
            <div class="ui center header">
                抱歉，我还不想有人注册这个网站。
            </div>
        </div>
    {% endblock %}
    </body>
</html>

blogs/templates/single-page.html
<!DOCTYPE HTML>
<html>
<head>
<title>Hexa</title>
<!-- Bootstrap -->
<link href="css/bootstrap.min.css" rel='stylesheet' type='text/css' />
<link href="css/bootstrap.css" rel='stylesheet' type='text/css' />
<meta name="viewport" content="width=device-width, initial-scale=1">
<script type="application/x-javascript"> addEventListener("load", function() { setTimeout(hideURLbar, 0); }, false); function hideURLbar(){ window.scrollTo(0,1); } </script>
 <!--[if lt IE 9]>
     <script src="js/html5shiv.js"></script>
     <script src="js/respond.min.js"></script>
<![endif]-->

<link href="css/style.css" rel="stylesheet" type="text/css" media="all" />
<!-- start plugins -->
<script type="text/javascript" src="js/jquery.min.js"></script>
	<script>
		$(function() {
			var pull 		= $('#pull');
				menu 		= $('nav ul');
				menuHeight	= menu.height();
			$(pull).on('click', function(e) {
				e.preventDefault();
				menu.slideToggle();
			});
			$(window).resize(function(){
        		var w = $(window).width();
        		if(w > 320 && menu.is(':hidden')) {
        			menu.removeAttr('style');
        		}
    		});
		});
	</script>
<!----font-Awesome----->
   	<link rel="stylesheet" href="fonts/css/font-awesome.min.css">
<!----font-Awesome----->
</head>
<body>
<div class="header_bg" id="home"><!-- start header -->
<div class="container">
	<div class="row header text-center specials">
		<div class="h_logo">
			<a href="index.html"><img src="images/logo.png" alt="" class="responsive"/></a>
		</div>
		<nav class="top-nav">
			<ul class="top-nav nav_list">
				<li><a href="portfolio.html">portfolio</a></li>
				<li class="page-scroll"><a href="index.html">About</a></li>
				<li class="logo page-scroll"><a title="hexa" href="index.html"><img src="images/logo.png" alt="" class="responsive"/></a></li>
			    <li class="page-scroll"><a href="blog.html">blog</a></li>
				<li class="page-scroll"><a href="#contact">get in touch</a></li>
			</ul>
			<a href="#" id="pull"><img src="images/nav-icon.png" title="menu" /></a>
		</nav>
		<div class="clearfix"></div>
	</div>
</div>
</div>
<div class="blog"><!-- start main -->
	<div class="container">
		<div class="main row">
			<h2 class="style">Lorem  use a passage of Lorem Ipsum</h2>
			<div class="details row">
				<div class="col-md-6">
					<img src="images/det_pic.jpg" alt="" class="img-responsive"/>
				</div>
				<div class="col-md-6">
					<p class="para">Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. </p>
					<p class="para">There are many variations of passages of Lorem Ipsum available, but the majority have suffered alteration in some form alteration in some form, by injected humour. If you are going to use a passage of Lorem Ipsum, you need to be sure there isn't anything embarrassing hidden in the middle of text. All the Lorem Ipsum generators on the Internet tend to repeat predefined chunks as necessary, making this the first true generator on the Internet.  </p>
				</div>
				<div class="clearfix"></div>
			</div>
			<p class="para">But I must explain to you how all this mistaken idea of denouncing pleasure and praising pain was born and I will give you a complete account of the system, and expound the actual teachings of the great explorer of the truth, the master-builder of human happiness. No one rejects, dislikes, or avoids pleasure itself, because it is pleasure, but because those who do not know how to pursue pleasure rationally encounter consequences that are extremely painful. Nor again is there anyone who loves or pursues or desires to obtain pain of itself, because it is pain, but because occasionally circumstances occur in which toil and pain can procure him some great pleasure. To take a trivial example, which of us ever undertakes laborious physical exercise, except to obtain some advantage from it? But who has any right to find fault with a man who chooses to enjoy a pleasure that has no annoying consequences, or one who avoids a pain that produces no resultant pleasure.</p>
			<div class="read_more">
				<a href="single-page.html">read more</a>
			</div>
		</div>
	</div>
</div><!-- end main -->
<div class="footer_bg" id="contact"><!-- start footer -->
<div class="container">
	<div class="row footer">
		<div class="col-md-8 contact_left">
			<h3>get in touch</h3>
			<p>In order to get in touch use the contact form below:</h4>
			<form method="post" action="contact-post.html">
				<input type="text" value="Name (Required)" onFocus="this.value = '';" onBlur="if (this.value == '') {this.value = 'Name';}">
				<input type="text" value="Email (Required)" onFocus="this.value = '';" onBlur="if (this.value == '') {this.value = 'Email';}">
				<input type="text" value="Subject" onFocus="this.value = '';" onBlur="if (this.value == '') {this.value = 'Subject';}">
				<textarea onFocus="if(this.value == 'Your Message here....') this.value='';" onBlur="if(this.value == '') this.value='Your Message here....;" >Your Message here....</textarea>
				<span class="pull-right"><input type="submit" value="submit us"></span>
			</form>
		</div>
		<div class="col-md-4  contact_right">
			<p><span>Lorem Ipsum is simply dummy text: </span> Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. </p>
			<ul class="list-unstyled address">
				<li><i class="fa fa-map-marker"></i><span>500 Lorem Ipsum Dolor Sit,</span></li>
				<li><i class="fa fa-phone"></i><span>(00) 222 666 444</span></li>
				<li><i class="fa fa-envelope"></i><a href="mailto:info@mycompany.com">info(at)mycompany.com</a></li>
			</ul>
		</div>		
	</div>
</div>
</div>
<div class="footer1_bg"><!-- start footer1 -->
	<div class="container">
		<div class="row  footer">
			<div class="copy text-center">
				<p class="link"><span>Copyright &copy; 2014.Company name All rights reserved.<a target="_blank" href="http://www.huiyi8.com/moban/">&#x7F51;&#x9875;&#x6A21;&#x677F;</a></span></p>
				<a href="#home" id="toTop" style="display: block;"><span id="toTopHover" style="opacity: 1;"> </span></a>
			</div>
		</div>
		<script type="text/javascript">
				$(function() {
				  $('a[href*=#]:not([href=#])').click(function() {
				    if (location.pathname.replace(/^\//,'') == this.pathname.replace(/^\//,'') && location.hostname == this.hostname) {
			
				      var target = $(this.hash);
				      target = target.length ? target : $('[name=' + this.hash.slice(1) +']');
				      if (target.length) {
				        $('html,body').animate({
				          scrollTop: target.offset().top
				        }, 1000);
				        return false;
				      }
				    }
				  });
				});
		</script>
		<!---- start-smoth-scrolling---->		
	</div>
</div>

</body>
</html>